apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lw2br0ysk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lw2br0ysk-go 
  name: lw2br0ysk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lw2br0ysk-go 
